<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <meta name="theme-color" content="#ffffff">
  <link rel="shortcut icon" href="/favicon.png" type="image/png">

  <title>Placeholder</title>

  <style type="text/css">

    html, body {
      margin: 0;
      padding: 0;
      font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;
      line-height: 2em;
    }

    div {

      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100vh

    }

    code {
      color: darkred;
      line-height: inherit;
    }

    p {
      text-align: center;
    }

  </style>

</head>
<body>
<div>
  <h1>Do not edit this file...</h1>
  <p>
    The content of this file will be overwritten every time by the production build task in the VUE CLI builder.<br/>
    <u>Any changes to this file will be lost!</u>
  </p>
  <p>To customise the output content of <strong>`app.blade.php`</strong> file please edit <code>/src/templates/app.blade.php</code> instead.</p>
</div>
</body>
</html>
